# These settings are used by the Python functions open_sdg_build() and
# open_sdg_check(), from sdg-build.

# List of languages for translated builds.
languages:
  - en

# Where the data gets built.
site_dir: _site

# The file to use for the metadata schema.
schema_file: _prose.yml

# The parent folder of the 'meta' and 'data' folders.
src_dir: ''

# Translation repositories
# ------------------------
# This tells sdg-build to import translations from Git repositories. Specific
# tags or branches should be indicated after an "@" symbol. The default is the
# GitHub repository 'sdg-translations'.
translations:
  - class: TranslationInputSdgTranslations
    source: https://github.com/open-sdg/sdg-translations.git
    tag: 1.0.0
  
inputs:
  - class: InputCsvData
    # This describes the data files, relative to the "src_dir" indicated above.
    path_pattern: data/*-*.csv
  - class: InputCsvMeta
    path_pattern: meta/*-*.xlsx
    metadata_mapping: 'metadata-mapping.csv'
  - class: InputYamlMdMeta
    # This describes the meta files, relative to the "src_dir" indicated above.
    path_pattern: meta/*-*.md

# Extra fields to generate reporting stats for, for additional tabs
# the "Reporting status" page.
reporting_status_extra_fields: []
