# These settings are used by the Python functions open_sdg_build() and
# open_sdg_check(), from sdg-build.

# List of languages for translated builds.
languages:
  - en

# Where the data gets built.
site_dir: _site

# The file to use for the metadata schema.
schema_file: _prose.yml

# The parent folder of the 'meta' and 'data' folders.
src_dir: ''

# Translation repositories
# ------------------------
# This tells sdg-build to import translations from Git repositories. Specific
# tags or branches should be indicated after an "@" symbol. The default is the
# GitHub repository 'sdg-translations'.
translations:
  - class: TranslationInputSdgTranslations
    source: https://github.com/open-sdg/sdg-translations.git
    tag: 1.4.0
  - class: TranslationInputYaml
    source: translations
  
inputs:
  - class: InputCsvData
    # This describes the data files, relative to the "src_dir" indicated above.
    path_pattern: data/*-*.csv
  - class: InputYamlMdMeta
    # This describes the meta files, relative to the "src_dir" indicated above.
    path_pattern: global-meta/*-*.md
  - class: InputCsvMeta
    path_pattern: csv-meta/*-*.csv
    metadata_mapping: 'metadata-mapping.csv'

map_layers:
#Country (https://geoportal.statistics.gov.uk/datasets/countries-december-2019-boundaries-uk-buc)
  - geojson_file: https://opendata.arcgis.com/datasets/92ebeaf3caa8458ea467ec164baeefa4_0.geojson
    name_property: ctry19nm
    id_property: ctry19cd
    output_subfolder: country
    filename_prefix: indicator_
#Region (link: https://hub.arcgis.com/datasets/4fcca2a47fed4bfaa1793015a18537ac_4)
  - geojson_file: https://geoportal1-ons.opendata.arcgis.com/datasets/4fcca2a47fed4bfaa1793015a18537ac_4.geojson
    name_property: rgn17nm
    id_property: rgn17cd
    output_subfolder: regions
    filename_prefix: indicator_
#Local Authority (link: https://hub.arcgis.com/datasets/686603e943f948acaa13fb5d2b0f1275_4)
  - geojson_file: https://geoportal1-ons.opendata.arcgis.com/datasets/686603e943f948acaa13fb5d2b0f1275_4.geojson
    name_property: lad16nm
    id_property: lad16cd
    output_subfolder: local_authorities
    filename_prefix: indicator_

# Map data notes
# Ward data can be identified at 
# https://hub.arcgis.com/datasets/ons::wards-december-2020-names-and-codes-in-the-united-kingdom/explore
# https://opendata.arcgis.com/datasets/85c824fc6b154f2c94d7a0cfbd268067_0.geojson

# Extra fields to generate reporting stats for, for additional tabs
# the "Reporting status" page.
reporting_status_extra_fields: []
