name: Deploy to staging

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Build data
      run: |
        python scripts/build_data.py
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.token }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true
    - name: Waiting 5 minutes for staging data deployment
      run: |
        sleep 300
    - name: Rebuild site
      run: |
        curl -X POST https://api.github.com/repos/sdg-bristol/sdg-site-bristol/dispatches \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Authorization: token ${{secrets.PAT_TOKEN}}" \
        --data '{"event_type": "rebuild-site"}'
